apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-deployment
  labels:
    app: rollout-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rollout-app
  template:
    metadata:
      labels:
        app: rollout-app
    spec:
      containers:
        - name: rollout-container
          image: ooghenekaro/argo-rollout:3
          ports:
            - name: http
              containerPort: 3000
  strategy:
    blueGreen:
      activeService: svc-active
      previewService: svc-preview
      autoPromotionEnabled: false
